# Generated by Django 3.2.15 on 2022-09-11 01:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={
                "verbose_name": "Скидка",
                "verbose_name_plural": "Скидки",
            },
        ),
        migrations.AddField(
            model_name="discount",
            name="amount_off",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Размер фиксированной скидки",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="name",
            field=models.CharField(
                default="name", max_length=128, verbose_name="Название"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tax",
            name="description",
            field=models.TextField(default="sdf", verbose_name="Описание"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tax",
            name="percentage",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="Налоговая ставка",
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="stripe_id",
            field=models.CharField(
                max_length=32, verbose_name="Stripe TaxRate ID"
            ),
        ),
    ]
