# Generated by Django 3.2.15 on 2022-09-11 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_auto_20220911_0124"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="duration",
            field=models.CharField(
                choices=[
                    ("forever", "Постоянный"),
                    ("once", "Одноразовый"),
                    ("repeating", "Временный"),
                ],
                default="once",
                max_length=16,
                verbose_name="Длительность действия",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="discount",
            name="duration_in_months",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                verbose_name="Длительность действия временной скидки",
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="max_redemptions",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Количество применений"
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="percent_off",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="Размер скидки в процентах",
            ),
        ),
    ]
